name: Lighthouse audit
on:
  push:
    paths-ignore:
      - '*.md'
      - 'package*.json'
  schedule:
    # every day at midnight (GMT)
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: treosh/lighthouse-ci-action@v3
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com
        env:
          LHCI_GITHUB_TOKEN: ${{ github.token }}

