name: Lighthouse audit
on:
  push:
    paths-ignore:
      - '*.md'
      - 'package*.json'
      - '.gitignore'
  schedule:
    # every day at midnight (GMT)
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-env name=LHCI_GITHUB_TOKEN::${{ github.token }}"
        if: github.event_name == 'push'

      - uses: ./.github/actions/setup-lhci
        if: github.event_name == 'schedule'

      - uses: treosh/lighthouse-ci-action@v3
        with:
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
          serverBaseUrl: https://lighthouse-ci-sfgov.herokuapp.com

